### ISSUE TITLE
"Your connection is not secure" when navigating to http://testrp.security.allizom.org/

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla-iam/testrp.security.allizom.org#28]
This is causing failures in auth0 tests
![con not secure](https://user-images.githubusercontent.com/5293100/39122962-1493907e-46ff-11e8-8404-271520370073.png)

**Comment by viorelaioia-zz** [comment]
CC: @gdestuynder , @andrewkrug

**Comment by gdestuynder** [comment]
certificates are refreshed periodically, then nginx restarts periodically to take them into account, except i didnt see anything that actually restarts it

i replaced the cron entry from gene by a systemd timer which reloads nginx when certs are renewed

note: testrp is not deployed or managed like a production host at this time
