### ISSUE TITLE
webroot/nginx/index.html contains HTTP reference

### ISSUE THREAD

**Issue by claudijd** [mozilla-iam/testrp.security.allizom.org#3]
webroot/nginx/index.html:64 contains an HTTP reference for something we could have as HTTPS.

            <li>How this test site is setup (with code, config, etc.): <a href="http://github.com/mozilla-iam/testrp.security.allizom.org/">http://github.com/mozilla-iam/testrp.security.allizom.org/</a></li>

We should use the HTTPS version of that.

**Comment by gdestuynder** [comment]
fixed thx!
