### ISSUE TITLE
Site does not follow our web/tls security guidelines

### ISSUE THREAD

**Issue by claudijd** [mozilla-iam/testrp.security.allizom.org#5]
When scanning this site with Observatory, we can see that we're missing a few key web security guidelines giving us an "F".

https://observatory.mozilla.org/analyze.html?host=testrp.security.allizom.org

We should really be practicing what we preach from a standards perspective.

**Comment by claudijd** [comment]
It seems it also doesn't conform out our TLS guidelines.

I'd like to suggest we shoot for "modern" TLS level and "A/A+" for web security level.

**Comment by gdestuynder** [comment]
See also https://mana.mozilla.org/wiki/display/SECURITY/Auth0+Proof+of+Concept+Report#Auth0ProofofConceptReport-Service&SupportTestResults

**Comment by gdestuynder** [comment]
Additionally, observatory results were C- (as recorded in the link above):

https://mozilla.github.io/http-observatory-website/analyze.html?host=mozilla.auth0.com (this no longer works iirc)

**Comment by gdestuynder** [comment]
config reloaded (grade intermediate for TLS - note, we test all kind of clients with it)

**Comment by gdestuynder** [comment]
fixed issues in the config commits up to e207e75199a346ee28a959e214d9b8eea6c14290
Current grade A+ on HTTP observatory, I on TLS observatory
